server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false表示自己就是注册中心 我都职责就是维护服务实例 并不需要去检索服务
    fetch-registry: false
    #不需要将自己注册进服务中心
    register-with-eureka: false
    #设置于eureka服务交互的地址 查询服务和注册服务都需要这个地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
